-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--###############
--## MONITORS ###
--###############

hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = 1,
})

hl.config({
    ecosystem = {
        no_update_news = true,
    },
})

--##################
--## MY PROGRAMS ###
--##################

local terminal = "kitty"
local vol = "pamixer --get-volume"

--################
--## AUTOSTART ###
--################

-- exec-once = $terminal
-- exec-once = nm-applet &

--############################
--## ENVIRONMENT VARIABLES ###
--############################

hl.env("XCURSOR_THEME", "miku-cursor")
hl.env("XCURSOR_SIZE", 32)
hl.env("HYPRCURSOR_SIZE", 32)

hl.env(
    "XCURSOR_PATH",
    "/usr/share/icons:/home/"
        .. os.getenv("USER")
        .. "/.icons:/home/"
        .. os.getenv("USER")
        .. "/.local/share/icons"
)

hl.env("HYPRCURSOR_MOVE", "fleur")

--####################
--## LOOK AND FEEL ###
--####################

hl.config({
    general = {
        gaps_in = 3,
        gaps_out = 5,
        border_size = 3,

        resize_on_border = true,
        allow_tearing = true,
        layout = "dwindle",

        col = {
            active_border = {
                colors = {
                    "rgba(1793d180)",
                    "rgba(1793d180)",
                },
                angle = 45,
            },

            inactive_border = "rgba(00000000)",
        },
    },
})

hl.config({
    decoration = {
        rounding = 10,
        rounding_power = 2,

        active_opacity = 1.0,
        inactive_opacity = 0.97,

        shadow = {
            enabled = true,
            range = 40,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },

        blur = {
            enabled = true,
            size = 3,
            passes = 1,
            vibrancy = 0.1696,
        },
    },
})

hl.config({
    animations = {
        enabled = true,
    },
})

--################
--## LAYOUTS #####
--################

hl.config({
    dwindle = {
        preserve_split = true,
    },
})

hl.config({
    master = {
        new_status = "master",
    },
})

hl.config({
    misc = {
        force_default_wallpaper = 2,
        disable_hyprland_logo = true,
    },
})

--############
--## INPUT ###
--############

hl.config({
    input = {
        kb_layout = "us",
        follow_mouse = 1,
        sensitivity = 0,

        touchpad = {
            natural_scroll = true,
        },
    },
})

hl.device({
    name = "vancer-vancer-akitsu-mouse",
    sensitivity = -0.5,
    accel_profile = "flat",
})

hl.device({
    name = "vancer-vancer-akitsu-mouse-consumer-control-1",
    sensitivity = -0.5,
    accel_profile = "flat",
})


--##################
--## KEYBINDINGS ###
--##################

local mainMod = "SUPER"

-- Terminal
hl.bind(
    mainMod .. " + " .. "Q",
    hl.dsp.exec_cmd("kitty")
)

-- Toggle floating
hl.bind(
    mainMod .. " + " .. "W",
    hl.dsp.window.float()
)

-- Screenshot
hl.bind(
    mainMod .. " + " .. "A",
    hl.dsp.exec_cmd(
        "grim -g \"$(slurp)\" ~/Pictures/Screenshots/screenshot.jpg"
    )
)

-- Close window
hl.bind(
    mainMod .. " + " .. "E",
    hl.dsp.window.close()
)

-- Exit Hyprland
hl.bind(
    mainMod .. " + " .. "M",
    hl.dsp.exit()
)

-- Fullscreen
hl.bind(
    mainMod .. " + " .. "F",
    hl.dsp.window.fullscreen()
)

-- Float
hl.bind(
    mainMod .. " + " .. "V",
    hl.dsp.window.float()
)

-- Switch keyboard layout
hl.bind(
    mainMod .. " + " .. "space",
    hl.dsp.exec_cmd(
        "sh -c \"hyprctl switchxkblayout at-translated-set-2-keyboard next\""
    )
)

-- Pseudo
hl.bind(
    mainMod .. " + " .. "P",
    hl.dsp.window.pseudo()
)

-- Toggle split
hl.bind(
    mainMod .. " + " .. "J",
    hl.dsp.layout("togglesplit")
)

-- Launcher
hl.bind(
    mainMod .. " + " .. "R",
    hl.dsp.exec_cmd("radiqctl toggle"))

-- Window switcher
hl.bind(
    mainMod .. " + " .. "TAB",
    hl.dsp.exec_cmd("rofi -show window")
)

-- Region screenshot
hl.bind(
    mainMod .. " + " .. "SHIFT" .. " + " .. "P",
    hl.dsp.exec_cmd("hyprshot -m region")
)
-- SUPER + I -> Restart Eww
hl.bind(
    mainMod .. " + I",
    hl.dsp.exec_cmd(
        "bash -lc '"
        .. "eww kill >/dev/null 2>&1 || true; "
        .. "pkill -f \"$HOME/.config/eww/scripts/getvol.sh\" 2>/dev/null || true; "
        .. "pkill -f \"$HOME/.config/eww/scripts/workspace.sh\" 2>/dev/null || true; "
        .. "pkill -x eww 2>/dev/null || true; "
        .. "sleep 1; "
        .. "EWW_CONFIG_DIR=\"$HOME/.config/eww\" /usr/bin/eww daemon >/dev/null 2>&1; "
        .. "sleep 0.7; "
        .. "EWW_CONFIG_DIR=\"$HOME/.config/eww\" /usr/bin/eww open bar_widget; "
        .. "EWW_CONFIG_DIR=\"$HOME/.config/eww\" /usr/bin/eww update get_vol=\"$(pamixer --get-volume)\"; "
        .. "$HOME/.config/eww/scripts/getvol.sh >/dev/null 2>&1 & "
        .. "$HOME/.config/eww/scripts/workspace.sh >/tmp/workspace.log 2>&1 &"
        .. "'"
    )
)

--#####################
--## FOCUS MOVEMENT ###
--#####################

hl.bind(
    mainMod .. " + " .. "left",
    hl.dsp.focus({ direction = "left" })
)

hl.bind(
    mainMod .. " + " .. "right",
    hl.dsp.focus({ direction = "right" })
)

hl.bind(
    mainMod .. " + " .. "up",
    hl.dsp.focus({ direction = "up" })
)

hl.bind(
    mainMod .. " + " .. "down",
    hl.dsp.focus({ direction = "down" })
)

--####################
--## WORKSPACES ######
--####################

-- SUPER + 1-6 switches workspace

hl.bind(
    mainMod .. " + " .. 1,
    hl.dsp.focus({ workspace = "1" })
)

hl.bind(
    mainMod .. " + " .. 2,
    hl.dsp.focus({ workspace = "2" })
)

hl.bind(
    mainMod .. " + " .. 3,
    hl.dsp.focus({ workspace = "3" })
)

hl.bind(
    mainMod .. " + " .. 4,
    hl.dsp.focus({ workspace = "4" })
)

hl.bind(
    mainMod .. " + " .. 5,
    hl.dsp.focus({ workspace = "5" })
)

hl.bind(
    mainMod .. " + " .. 6,
    hl.dsp.focus({ workspace = "6" })
)

-- SUPER + 0 -> workspace 10

hl.bind(
    mainMod .. " + " .. 0,
    hl.dsp.focus({ workspace = "10" })
)

--###################################
--## MOVE WINDOWS TO WORKSPACES #####
--###################################

-- SUPER + SHIFT + 1-6

hl.bind(
    mainMod .. " + " .. "SHIFT" .. " + " .. 1,
    hl.dsp.window.move({ workspace = "1" })
)

hl.bind(
    mainMod .. " + " .. "SHIFT" .. " + " .. 2,
    hl.dsp.window.move({ workspace = "2" })
)

hl.bind(
    mainMod .. " + " .. "SHIFT" .. " + " .. 3,
    hl.dsp.window.move({ workspace = "3" })
)

hl.bind(
    mainMod .. " + " .. "SHIFT" .. " + " .. 4,
    hl.dsp.window.move({ workspace = "4" })
)

hl.bind(
    mainMod .. " + " .. "SHIFT" .. " + " .. 5,
    hl.dsp.window.move({ workspace = "5" })
)

hl.bind(
    mainMod .. " + " .. "SHIFT" .. " + " .. 6,
    hl.dsp.window.move({ workspace = "6" })
)

-- SUPER + SHIFT + 0 -> workspace 10

hl.bind(
    mainMod .. " + " .. "SHIFT" .. " + " .. 0,
    hl.dsp.window.move({ workspace = "10" })
)

--##################
--## LOCK SCREEN ###
--##################

hl.bind(
    mainMod .. " + " .. "L",
    hl.dsp.exec_cmd(
        os.getenv("HOME")
            .. "/.config/hyprlock/scripts/hyprlock.sh"
    )
)

--########################
--## SPECIAL WORKSPACE ###
--########################

hl.bind(
    mainMod .. " + " .. "S",
    hl.dsp.workspace.toggle_special("magic")
)

hl.bind(
    mainMod .. " + " .. "SHIFT" .. " + " .. "S",
    hl.dsp.window.move({
        workspace = "special:magic",
    })
)

--##########################
--## WORKSPACE SCROLLING ###
--##########################

hl.bind(
    mainMod .. " + " .. "mouse_down",
    hl.dsp.focus({
        workspace = "e+1",
    })
)

hl.bind(
    mainMod .. " + " .. "mouse_up",
    hl.dsp.focus({
        workspace = "e-1",
    })
)

--##########################
--## MOVE / RESIZE MOUSE ###
--##########################

hl.bind(
    mainMod .. " + " .. "mouse:272",
    hl.dsp.window.drag(),
    {
        mouse = true,
    }
)

hl.bind(
    mainMod .. " + " .. "mouse:273",
    hl.dsp.window.resize(),
    {
        mouse = true,
    }
)

--#########################
--## MULTIMEDIA KEYS ######
--#########################

hl.bind(
    "XF86AudioRaiseVolume",
    hl.dsp.exec_cmd(
        "wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"
    ),
    {
        locked = true,
    }
)

hl.bind(
    "XF86AudioLowerVolume",
    hl.dsp.exec_cmd(
        "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
    ),
    {
        locked = true,
    }
)

hl.bind(
    "XF86AudioMute",
    hl.dsp.exec_cmd(
        "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
    ),
    {
        locked = true,
    }
)

hl.bind(
    "XF86AudioMicMute",
    hl.dsp.exec_cmd(
        "wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"
    ),
    {
        locked = true,
    }
)

hl.bind(
    "XF86MonBrightnessUp",
    hl.dsp.exec_cmd(
        "brightnessctl s 10%+"
    ),
    {
        locked = true,
    }
)

hl.bind(
    "XF86MonBrightnessDown",
    hl.dsp.exec_cmd(
        "brightnessctl s 10%-"
    ),
    {
        locked = true,
    }
)

hl.bind(
    "XF86AudioNext",
    hl.dsp.exec_cmd("playerctl next"),
    {
        locked = true,
    }
)

hl.bind(
    "XF86AudioPause",
    hl.dsp.exec_cmd("playerctl play-pause"),
    {
        locked = true,
    }
)

hl.bind(
    "XF86AudioPlay",
    hl.dsp.exec_cmd("playerctl play-pause"),
    {
        locked = true,
    }
)

hl.bind(
    "XF86AudioPrev",
    hl.dsp.exec_cmd("playerctl previous"),
    {
        locked = true,
    }
)

--#############################
--## WINDOWS AND WORKSPACES ###
--#############################

-- Example:
-- windowrule = float, ^(kitty)$
-- windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

--########################
--## OSU LOW LATENCY #####
--########################

hl.window_rule({
    name = "osu-low-latency",
    match = {
        class = "sh.ppy.osu",
    },
    immediate = true,
})

--########################
--## LAYER RULES #########
--########################

-- Keep Eww above mpvpaper
hl.layer_rule({
    match = {
        namespace = "gtk-layer-shell",
    },
    order = -10,
})

-- Keep wallpaper behind Eww
hl.layer_rule({
    match = {
        namespace = "mpvpaper",
    },
    order = 10,
})

hl.layer_rule({
    match = {
        namespace = "radiq",
    },
    order = 100,
})

--################
--## AUTOSTART ###
--################

hl.on("hyprland.start", function()

    
    hl.exec_cmd("radiqd &")
    hl.exec_cmd("/usr/lib/kdeconnectd")
    hl.exec_cmd("bluetoothctl power on")
    hl.exec_cmd("blueman-applet")

    -- Wallpaper
    hl.exec_cmd(
        "bash -lc '"
        .. "swww-daemon >/dev/null 2>&1 & "
        .. "sleep 0.5; "
        .. "waypaper --restore >/dev/null 2>&1 &"
        .. "'"
    )

    -- Eww
    hl.exec_cmd(
        "bash -lc '"
        .. "sleep 0.1; "
        .. "EWW_CONFIG_DIR=\"$HOME/.config/eww\" /usr/bin/eww daemon; "
        .. "sleep 0.5; "
        .. "EWW_CONFIG_DIR=\"$HOME/.config/eww\" /usr/bin/eww open bar_widget; "
        .. "EWW_CONFIG_DIR=\"$HOME/.config/eww\" /usr/bin/eww update get_vol=\"$(pamixer --get-volume)\"; "
        .. "$HOME/.config/eww/scripts/getvol.sh >/dev/null 2>&1 & "
        .. "$HOME/.config/eww/scripts/workspace.sh >/tmp/workspace.log 2>&1 &"
        .. "'"
    )

    -- Idle daemon
    hl.exec_cmd("hypridle")

    -- Text animation
    hl.exec_cmd("sh ~/.config/hypr/scripts/text_animation/anitext.sh")

    -- Weather
    hl.exec_cmd("sh ~/.config/hypr/scripts/weather/weather.sh")

    -- Japanese input
    hl.exec_cmd("fcitx5 -d")
end)
