-- Generated by nwg-displays on 2026-09-02 at 13:37:19. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1200@60.0",
    position = "0x0",
    scale = 1.0,
    mirror = "10"
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "1920x0",
    scale = 1,
    mirror = "10"
})
